# generated by scripts/release-local.sh for v1.2.6 — do not edit by hand
cask "llmpilot" do
  version "1.2.6"
  sha256 "3e55effb9ed531c1f4237122aa8b80d12ced64ed34d95f1fa72c1db4d81dca2f"

  url "https://github.com/alicicek/llmpilot/releases/download/v#{version}/llmpilot-#{version}.zip",
      verified: "github.com/alicicek/llmpilot/"
  name "llmpilot"
  desc "Multi-account Claude Code companion — the menu bar app"
  homepage "https://llmpilot.dev/"

  auto_updates true

  app "llmpilot.app"

  zap trash: "~/.llmpilot"
end
