# generated by scripts/release-local.sh for v1.2.5 — do not edit by hand
cask "llmpilot" do
  version "1.2.5"
  sha256 "e9ca991174b2b429ec6bca0d082a4daf5b2889d382eddcd1bad43bdbbe3077fe"

  url "https://github.com/alicicek/llmpilot/releases/download/v#{version}/llmpilot-#{version}.zip",
      verified: "github.com/alicicek/llmpilot/"
  name "llmpilot"
  desc "Multi-account Claude Code companion — the menu bar app"
  homepage "https://llmpilot.dev/"

  auto_updates true

  app "llmpilot.app"

  zap trash: "~/.llmpilot"
end
