# generated by scripts/release-local.sh for v1.3.6 — do not edit by hand
cask "llmpilot" do
  version "1.3.6"
  sha256 "93e9464c41167f30c75cf3254e7de6e36237bcd240cd21acceb01015ae7050d9"

  url "https://github.com/alicicek/llmpilot/releases/download/v#{version}/llmpilot-#{version}.zip",
      verified: "github.com/alicicek/llmpilot/"
  name "llmpilot"
  desc "Multi-account Claude Code companion — the menu bar app"
  homepage "https://llmpilot.dev/"

  auto_updates true

  app "llmpilot.app"

  zap trash: "~/.llmpilot"
end
