# generated by scripts/release-local.sh for v1.4.1 — do not edit by hand
class Llmpilot < Formula
  desc "Multi-account Claude Code companion — usage, switching, scheduling"
  homepage "https://llmpilot.dev"
  license "MIT"
  version "1.4.1"

  if Hardware::CPU.arm?
    url "https://github.com/alicicek/llmpilot/releases/download/v1.4.1/llmpilot_1.4.1_darwin_arm64.tar.gz"
    sha256 "052962282aa152472c5575458e3b4651f6705450789770ec2ac0f11b104fe856"
  else
    url "https://github.com/alicicek/llmpilot/releases/download/v1.4.1/llmpilot_1.4.1_darwin_amd64.tar.gz"
    sha256 "f016b276ba974e31ee0a8aafa7812ee8298c404f3cb802d55d9cf84b5aa610e3"
  end

  def install
    bin.install "llmpilot"
  end

  test do
    system "#{bin}/llmpilot", "--version"
  end
end
