# generated by scripts/release-local.sh for v1.3.1 — do not edit by hand
class Llmpilot < Formula
  desc "Multi-account Claude Code companion — usage, switching, scheduling"
  homepage "https://llmpilot.dev"
  license "MIT"
  version "1.3.1"

  if Hardware::CPU.arm?
    url "https://github.com/alicicek/llmpilot/releases/download/v1.3.1/llmpilot_1.3.1_darwin_arm64.tar.gz"
    sha256 "c004b2d2b6cff0dd8a1e344c4794fd280cefbe4589ec1d6ad8df0e42efc4c60f"
  else
    url "https://github.com/alicicek/llmpilot/releases/download/v1.3.1/llmpilot_1.3.1_darwin_amd64.tar.gz"
    sha256 "627cb8c96166a2300e3f8cee59be3eaecbf019931a8ffdaf31d17857f44c4873"
  end

  def install
    bin.install "llmpilot"
  end

  test do
    system "#{bin}/llmpilot", "--version"
  end
end
