# generated by scripts/release-local.sh for v1.3.3 — do not edit by hand
class Llmpilot < Formula
  desc "Multi-account Claude Code companion — usage, switching, scheduling"
  homepage "https://llmpilot.dev"
  license "MIT"
  version "1.3.3"

  if Hardware::CPU.arm?
    url "https://github.com/alicicek/llmpilot/releases/download/v1.3.3/llmpilot_1.3.3_darwin_arm64.tar.gz"
    sha256 "bf9177bb1492d53835b254a810392e761b5efca3d862e872aa0c081d0fc72abe"
  else
    url "https://github.com/alicicek/llmpilot/releases/download/v1.3.3/llmpilot_1.3.3_darwin_amd64.tar.gz"
    sha256 "884e2c1068959fc628e01e7d245413f57d1cccda75c36fc4382c8f8f737202d1"
  end

  def install
    bin.install "llmpilot"
  end

  test do
    system "#{bin}/llmpilot", "--version"
  end
end
